config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users, only: [:new, :create, :show, :index] do
    resources :comments, only: [:create]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :goals, only: [:new, :create, :show] do
    resources :comments, only: [:create]
    resources :cheers, only: [:create, :destroy]

    member do
      post :complete
      post :incomplete
    end

    collection do
      get :leaderboard
    end
  end
end

app/models/cheer.rb
class Cheer < ActiveRecord::Base
  validates :user, :goal, presence: true

  belongs_to :user
  belongs_to :goal

  def self.create_cheers(user, goal)
    if user.has_remaining_cheers?
      Cheer.create!(user: user, goal: goal)
      user.cheers_goal
    end
  end

  def self.destroy_cheers(user, goal)
    if user.has_cheersed_goal?(goal)
      cheer = Cheer.find_by(user: user, goal: goal)
      cheer.destroy! if cheer
      user.uncheers_goal
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :author, :body, :commentable, presence: true

  belongs_to :author, class_name: "User"
  belongs_to :commentable, polymorphic: true
end

app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable
  end

  def tag_names
    tags.map(&:name)
  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  include Commentable

  validates :user, :title, presence: true
  validates :public, :complete, inclusion: { in: [ true, false ] }

  belongs_to :user
  has_many :cheers

  def self.top_goals
    Goal.select("goals.*, COUNT(cheers.id) as cheers_count")
        .joins(:cheers)
        .group("goals.id")
        .limit(10)
        .order("cheers_count DESC")
  end

  def cheers_count
    Cheer.where(goal: self).count
  end
end

app/models/goal_comment.rb
class GoalComment < ActiveRecord::Base
  validates :goal, :author, :body, presence: true

  belongs_to :goal
  belongs_to :author, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  include Commentable

  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :goals
  has_many :authored_comments, class_name: "Comment", foreign_key: :author_id
  has_many :cheers_given, class_name: "Cheers"

  def self.find_by_username_and_password(username, password)
    user = User.find_by_username(username)
    user && user.is_password?(password) ? user : nil
  end

  def self.top_users
    query = <<-SQL
      SELECT
        users.*, COUNT(cheers.id) AS cheers_count
      FROM
        users
      JOIN
        goals ON goals.user_id = users.id
      JOIN
        cheers ON cheers.goal_id = cheers.id
      GROUP BY
        users.id
      ORDER BY
        COUNT(cheers.id) DESC
      LIMIT
        10
    SQL

    User.find_by_sql(query)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
    self.save
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def has_remaining_cheers?
    self.cheers_count > 0
  end

  def has_cheersed_goal?(goal)
    !!Cheer.find_by(user: self, goal: goal)
  end

  def cheers_goal
    self.cheers_count -= 1
    self.save
  end

  def uncheers_goal
    self.cheers_count += 1
    self.save
  end

  private
  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end
end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base
  validates :user, :author, :body, presence: true

  belongs_to :user
  belongs_to :author, class_name: "User"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?
  helper_method :current_user

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout_user!(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def current_user
    session[:session_token] ? User.find_by_session_token(session[:session_token]) : nil
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

  def require_logged_in!
    redirect_to users_url unless logged_in?
  end
end

app/controllers/cheers_controller.rb
class CheersController < ApplicationController
  def create
    Cheer.create_cheers(current_user, Goal.find(params[:goal_id]))

    redirect_to goal_url(params[:goal_id])
  end

  def destroy
    Cheer.destroy_cheers(current_user, Goal.find(params[:goal_id]))

    redirect_to goal_url(params[:goal_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    if params[:user_id]
      @comment.commentable_id = params[:user_id]
      @comment.commentable_type = "User"
      redirect_url = user_url(params[:user_id])
    else
      @comment.commentable_id = params[:goal_id]
      @comment.commentable_type = "Goal"
      redirect_url = goal_url(params[:goal_id])
    end
    @comment.save

    redirect_to redirect_url
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_logged_in!

  def new
    @goal = Goal.new

    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    @goal.complete = false

    if @goal.save
      redirect_to user_url(current_user)
    else
      flash[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])

    render :show
  end

  def complete
    @goal = Goal.find(params[:id])
    @goal.complete = true
    @goal.save

    redirect_to goal_url(@goal)
  end

  def incomplete
    @goal = Goal.find(params[:id])
    @goal.complete = false
    @goal.save

    redirect_to goal_url(@goal)
  end

  def leaderboard
    @goals = Goal.top_goals
    @users = User.top_users

    render :leaderboard
  end

  private
  def goal_params
    params.require(:goal).permit(:title, :body, :public)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.find_by_username_and_password(user_params[:username], user_params[:password])

    if @user
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = "invalid credentials"
      render :new
    end
  end

  def destroy
    logout_user!(current_user) if current_user
    redirect_to users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    render :index
  end

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      login_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @private_goals = []

    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    html = "<input type='hidden' " +
           "name='authenticity_token'" +
           "value='#{form_authenticity_token}'>"

    html.html_safe
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/leaderboard.html.erb
<h3>Top Goals</h3>
<table>
  <tr>
    <th>Rank</th>
    <th>Goal</th>
    <th>Total Cheers</th>
  </tr>
  <% @goals.each_with_index do |g, idx| %>
  <tr>
    <td><%= idx + 1 %></td>
    <td><%= link_to g.title, goal_url(g) %></td>
    <td><%= g.cheers_count %></td>
  </tr>
  <% end %>
</table>

<h3>Top Users</h3>
<table>
  <tr>
    <th>Rank</th>
    <th>Goal</th>
    <th>Total Cheers</th>
  </tr>
  <% @users.each_with_index do |u, idx| %>
  <tr>
    <td><%= idx + 1 %></td>
    <td><%= link_to u.username, user_url(u) %></td>
    <td><%= u.cheers_count %></td>
  </tr>
  <% end %>
</table>

app/views/goals/new.html.erb
<h3>Add Goal</h3>
<form action="<%= goals_url %>" method="post">
<%= auth_token %>
<label>Title<input type="text" name="goal[title]"></label>
<br>
<label>Body<textarea name="goal[body]"></textarea></label>
<br>
<label>
<input type="radio" name="goal[public]" value="false" checked>Private</label>
<label>
<input type="radio" name="goal[public]" value="true">Public</label>
<br>
<input type="submit" value="submit">
</form>

app/views/goals/show.html.erb
<h3>
  <%= @goal.title %>
</h3>
<h4>
  by <%= @goal.user.username %>
</h4>
<p>
<%= @goal.body %>
</p>
<% if @goal.complete %>
  <h4>
    Status: complete
  </h4>
  <%= button_to "incomplete goal", incomplete_goal_url(@goal) %>
<% else %>
  <h4>
    Status: incomplete
  </h4>
  <%= button_to "complete goal", complete_goal_url(@goal) %>
<% end %>
<h3>Cheers: <%= @goal.cheers_count %></h3>
<% if current_user.has_remaining_cheers? %>
<%= button_to "add cheers", goal_cheers_url(@goal.id), method: :post %>
<% end %>
<% if current_user.has_cheersed_goal?(@goal) %>
<%= button_to "remove cheers", goal_cheer_url(@goal.id, 1), method: :delete %>
<% end %>
<h3>Comments</h3>
<ul>
<% @goal.comments.each do |c| %>
<li><%= c.body %></li>
<% end %>
</ul>
<form action="<%= goal_comments_url(@goal.id) %>" method="post">
<%= auth_token %>
<label class="comment-label">Comment:
<textarea class="comment-body" name="comment[body]" rows="8" cols="80"></textarea>
</label>
<input type="submit" value="submit">
</form>
<br>
<%= link_to "back to #{@goal.user.username}", user_url(@goal.user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalsApp</title>
  <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <% if logged_in? %>
    <span class="welcome">Welcome, <%= current_user.username %></span>
    <span class="logout-button"><%= button_to "Logout", session_url, method: :delete %></span>
    <div class="user-cheers-remaining">
      Cheers Remaining: <%= current_user.cheers_count %>
    </div>
    <% else %>
    <%= link_to "Sign Up", new_user_url %>
    <%= link_to "Sign In", new_session_url %>
    <% end %>
  </nav>
</header>
<section>
<%= yield %>
</section>
<footer>
  <% unless current_page?(leaderboard_goals_url)  %>
  <%= link_to "leaderboard", leaderboard_goals_url %>
  <% end %>
  <% unless current_page?(users_url)  %>
  <%= link_to "home", users_url %>
  <% end %>
</footer>
</body>
</html>

app/views/users/index.html.erb
<h3>All Users</h3>
<ul>
  <% @users.each do |u| %>
  <li><%= link_to u.username, user_url(u) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h3>Sign Up</h3>
<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label for="user_username">Username</label>
  <input type="text" name="user[username]" value="" id="user_username">
  <label for="user_password">Password</label>
  <input type="password" name="user[password]" value="" id="user_password">
  <input type="submit" value="submit">
</form>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<h3>Goals</h3>
<% if current_user && @user == current_user %>
<%= button_to "Add Goal", new_goal_url, method: :get %>
<% end %>
<ul>
<% @user.goals.each do |g| %>
  <% if g.public %>
    <li><%= link_to g.title, goal_url(g) %></li>
  <% else %>
    <% @private_goals << g %>
  <% end %>
<% end %>
</ul>
<% if current_user && @user == current_user %>
  <h4>Private Goals</h4>
  <ul>
  <% @private_goals.each do |pg| %>
    <li><%= link_to pg.title, goal_url(pg) %></li>
  <% end %>
  </ul>
<% end %>
<h3>Comments</h3>
<ul>
<% @user.comments.each do |c| %>
<li><%= c.body %></li>
<% end %>
</ul>
<form action="<%= user_comments_url(@user.id) %>" method="post">
<%= auth_token %>
<label class="comment-label">Comment:
<textarea class="comment-body" name="comment[body]" rows="8" cols="80"></textarea>
</label>
<input type="submit" value="submit">
</form>